package arcp

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// TestProtocolCorpus is the Go half of the byte-parity guarantee with
// agent/arcp.py. It loads tests/protocol_corpus.json (generated by
// cmd/gen-corpus) and verifies that, for every input envelope:
//
//  1. Signing with the corpus PSK produces the recorded sig_hex.
//  2. The canonical signing input matches canonical_hex.
//  3. Framing the signed envelope produces framed_hex.
//
// The Python suite at agent/tests/test_corpus.py loads the same corpus and
// asserts the same things; if both suites pass, byte parity is maintained.
func TestProtocolCorpus(t *testing.T) {
	corpus := loadCorpus(t)
	psk, err := hex.DecodeString(corpus.PSKHex)
	if err != nil {
		t.Fatalf("decode psk_hex: %v", err)
	}

	for _, c := range corpus.Tests {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			t.Parallel()

			// Build an Envelope from the input map. Round-trip through JSON
			// to preserve number types (Go uses float64 for unmarshaled JSON
			// numbers, which is what the agent will see too).
			env := envelopeFromMap(t, c.Envelope)

			// Sign and check sig.
			if err := Sign(env, psk); err != nil {
				t.Fatalf("Sign: %v", err)
			}
			if env.Auth.Sig != c.SigHex {
				t.Fatalf("sig mismatch:\n got %s\nwant %s", env.Auth.Sig, c.SigHex)
			}

			// Re-blank sig and check canonical bytes.
			env.Auth.Sig = ""
			canon, err := env.Marshal()
			if err != nil {
				t.Fatalf("Marshal canonical: %v", err)
			}
			gotCanonHex := hex.EncodeToString(canon)
			if gotCanonHex != c.CanonicalHex {
				t.Fatalf("canonical mismatch:\n got %s\nwant %s", gotCanonHex, c.CanonicalHex)
			}

			// Re-sign and check framed bytes.
			if err := Sign(env, psk); err != nil {
				t.Fatalf("Sign 2: %v", err)
			}
			var framed bytes.Buffer
			if err := WriteFrame(&framed, env); err != nil {
				t.Fatalf("WriteFrame: %v", err)
			}
			gotFramedHex := hex.EncodeToString(framed.Bytes())
			if gotFramedHex != c.FramedHex {
				t.Fatalf("framed mismatch:\n got %s\nwant %s", gotFramedHex, c.FramedHex)
			}

			// VerifySig must accept the recorded sig.
			if err := VerifySig(env, psk); err != nil {
				t.Fatalf("VerifySig: %v", err)
			}
		})
	}
}

type corpusFile struct {
	Schema string                 `json:"schema"`
	PSKHex string                 `json:"psk_hex"`
	Tests  []corpusCorpusTestCase `json:"tests"`
}

type corpusCorpusTestCase struct {
	Name         string         `json:"name"`
	Description  string         `json:"description"`
	Envelope     map[string]any `json:"envelope"`
	CanonicalHex string         `json:"canonical_hex"`
	SigHex       string         `json:"sig_hex"`
	FramedHex    string         `json:"framed_hex"`
}

func loadCorpus(t *testing.T) *corpusFile {
	t.Helper()

	// Walk up from this test file to the repo root, then into tests/.
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")
	corpusPath := filepath.Join(repoRoot, "tests", "protocol_corpus.json")

	data, err := os.ReadFile(corpusPath)
	if err != nil {
		t.Fatalf("read corpus %s: %v", corpusPath, err)
	}
	var c corpusFile
	if err := json.Unmarshal(data, &c); err != nil {
		t.Fatalf("unmarshal corpus: %v", err)
	}
	if c.Schema != "xpc.protocol.corpus.v1" {
		t.Fatalf("unexpected schema: %s", c.Schema)
	}
	if len(c.Tests) == 0 {
		t.Fatal("empty corpus")
	}
	return &c
}

func envelopeFromMap(t *testing.T, m map[string]any) *Envelope {
	t.Helper()
	// Round-trip through JSON to populate the typed Envelope struct.
	b, err := json.Marshal(m)
	if err != nil {
		t.Fatalf("marshal map: %v", err)
	}
	var e Envelope
	if err := json.Unmarshal(b, &e); err != nil {
		t.Fatalf("unmarshal envelope: %v", err)
	}
	if e.Payload == nil {
		e.Payload = map[string]any{}
	}
	// Sanity: corpus envelopes always have sig=""; Sign should fill it.
	if e.Auth.Sig != "" {
		panic(fmt.Sprintf("corpus envelope %q already has sig", e.ID))
	}
	return &e
}
