# -*- coding: utf-8 -*-
"""Python half of the protocol-byte-parity guarantee.

Loads tests/protocol_corpus.json (generated by cmd/gen-corpus) and verifies
that for every input envelope, signing with the corpus PSK produces the
recorded sig_hex, the canonical bytes match canonical_hex, and the framed
wire bytes match framed_hex. The Go counterpart lives in
internal/arcp/corpus_test.go.

If both suites are green, Go and Python produce byte-identical output for
every message type in the corpus.
"""
from __future__ import absolute_import

import binascii
import io
import json
import os
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
AGENT_DIR = os.path.dirname(HERE)
sys.path.insert(0, AGENT_DIR)

import arcp  # noqa: E402

REPO_ROOT = os.path.dirname(AGENT_DIR)
CORPUS_PATH = os.path.join(REPO_ROOT, "tests", "protocol_corpus.json")


@pytest.fixture(scope="module")
def corpus():
    with open(CORPUS_PATH, "rb") as f:
        return json.loads(f.read().decode("utf-8"))


@pytest.fixture(scope="module")
def psk(corpus):
    return binascii.unhexlify(corpus["psk_hex"])


def test_corpus_schema(corpus):
    assert corpus["schema"] == "xpc.protocol.corpus.v1"
    assert len(corpus["tests"]) > 0


@pytest.mark.parametrize("case_idx", range(8))
def test_corpus_case(corpus, psk, case_idx):
    if case_idx >= len(corpus["tests"]):
        pytest.skip("no case at index {0}".format(case_idx))
    case = corpus["tests"][case_idx]

    envelope = case["envelope"]
    # The envelope in the corpus always has auth.sig blanked. Our sign() must
    # fill it in to match sig_hex exactly.
    assert envelope["auth"]["sig"] == ""

    # Sign and check sig.
    arcp.sign(envelope, psk)
    assert envelope["auth"]["sig"] == case["sig_hex"], (
        "case {0!r}: sig mismatch:\n got {1}\nwant {2}".format(
            case["name"], envelope["auth"]["sig"], case["sig_hex"])
    )

    # Re-blank sig and check canonical bytes.
    envelope["auth"]["sig"] = ""
    canon = arcp.canonical_marshal(arcp._strip_empty_optionals(envelope))
    got_canon_hex = binascii.hexlify(canon).decode("ascii")
    assert got_canon_hex == case["canonical_hex"], (
        "case {0!r}: canonical mismatch:\n got {1}\nwant {2}".format(
            case["name"], got_canon_hex, case["canonical_hex"])
    )

    # Re-sign and check framed bytes.
    arcp.sign(envelope, psk)
    buf = io.BytesIO()
    arcp.write_frame(buf, envelope)
    got_framed_hex = binascii.hexlify(buf.getvalue()).decode("ascii")
    assert got_framed_hex == case["framed_hex"], (
        "case {0!r}: framed mismatch:\n got {1}\nwant {2}".format(
            case["name"], got_framed_hex, case["framed_hex"])
    )

    # verify_sig must accept the recorded sig.
    arcp.verify_sig(envelope, psk)
